Repository dxFeed/dxfeed-python-api, pull requests merged in 2020-04, with the labels that each got.

#3 En 1335 correct samples and doc
  README.md
  docs/basic_usage.rst
  docs/conf.py
  docs/custom_listener.rst
  docs/installation.rst
  examples/CustomListenerExample.ipynb
  pyproject.toml
Labels: documentation

#4 [EN-1335] data for publishing added
  pyproject.toml
Labels: documentation

#5 [EN-1228] ci cd
  .github/workflow/pythonpackage.yml
  README.md
Labels: enhancement

#2 [EN-1290] add macos support
  README.md
  build.py
  docs/installation.rst
  pyproject.toml
  tests/conftest.py
Labels: enhancement

#7 [EN-1413] Fixed segfault, fixed fixture
  dxfeed/core/DXFeedPy.pyx
  tests/test_dxfeedpy.py
Labels: bug
